name: FireSafeTotems
version: 1.0
main: com.example.firesafetotems.FireSafeTotemsPlugin
api-version: '1.20'
authors: [ 'ChatGPT' ]
description: Prevents Totems of Undying from burning in fire or lava
